### ISSUE TITLE
Is abipy actually a dependency

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#1]
You mention abipy in the readme as a dependency and you also import it in your examples and library code. However, it doesn't seem that you actually use abipy anywhere? 

If that is the case you can remove all the imports and update the readme.

**Comment by savya10** [comment]
Yeah, I noticed that and removed abipy from the imports, guess I forgot to commit the change. The only dependency of AbiPy right now is its gaussian function (used in the JDOS iterator) - but I'm sure we can just use one from another, more well-known package instead.

**Comment by savya10** [comment]
Removed all abipy imports aside from the gaussian function now

**Comment by utf** [comment]
I would just copy the function from abipy into your package. It is not a complicated function and is only a few lines.

**Comment by savya10** [comment]
Done :)
