### ISSUE TITLE
api should be an optional argument

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#10]
The Materials Project API key should be an optional argument with a default value of `None` here: https://github.com/WMD-group/PyTASER/blob/953968c3f0044e79644744415b33647dc7b2dae3/generator.py#L592

That's because, you can set the API in your `~/.pmgrc` file and it will be used automatically so you don't have to provide it to the function. You can do that on your system by typing `pmg config -a PMG_MAPI_KEY` on the command line in an environment with pymatgen installed. You should change `PMG_MAPI_KEY` to your API key.

Can you also:
1. Rename `api` to `api_key` as api is not clear.
2. Remove your API key from all the examples. In general you don't want anyone else to know your API key as it can be used to impersonate yourself. You can make it the default value of None in the examples and add a comment to explain more. E.g.

```python
api_key = None  # Use your API key here
GaAs_generator = generator.TASGenerator.from_mpid(
   "mp-2534", gaas_temp, gaas_conc, bandgap, api_key=api_key
)
```

**Comment by savya10** [comment]
Done!
