### ISSUE TITLE
Package needs documentation

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#16]
We need to create a documentation website or just have more details on how to run the code in the readme. An example of a package with a good readme is [effmass](https://github.com/lucydot/effmass)

If we want to submit to JOSS then having good documentation will be essential.

**Comment by savya10** [comment]
Created a local documentation website, still need to make a link for it using GitHub Pages. It is also not formatted much as of yet - would it be ok to use the documentation of IFermi as a base for what to build for this one? I have been swamped with my MSci project as of late, so haven't had time to format as much as I hoped.

**Comment by utf** [comment]
Yeah, definitely copy the IFermi format! No need to do everything from scratch.
