### ISSUE TITLE
Package needs tests

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#17]
We need unit tests to check that the package is running properly and to prevent further changes breaking the code.

The modern way to write tests in python is using [pytest](https://docs.pytest.org/en/6.2.x/)

You can see an example of how tests should be setup by looking at the evgraf repo (although actually the test files should begin with the prefix `test_`): https://github.com/pmla/evgraf/tree/master/tests

If we want to submit to JOSS then having tests will be essential.

**Comment by savya10** [comment]
All done! I have tried to use a simple bandstructure with silicon (mp-165), as well as a small energy mesh and simple calculations, but it might be good to use a material with less bands to simplify the data and speed up the tests. 

Tests have been done for `generator` and `plotter`, along with some slight changes for both of these modules to optimise them further. I avoided doing tests for `tas.py` and `kpoints` as `tas` is just a container class, and @utf assured me `kpoints` was ok. 

Some parts have been commented with hashes- @utf @aronwalsh could you please have a read? I implemented some things  that seem desirable/better to me, but your input on this would be better.
