### ISSUE TITLE
Remove .DS_Store and .idea folders and add .gitignore

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#18]
Mac OS writes .DS_Store files for caching information about folders you visit in finder. Also PyCharm writes the `.idea` folder for storing information about the pycharm project.

Typically you don't want either of these in a git repo. The easiest way to handle them is using a .gitignore file in the root directory of the project which states which files to ignore.

To fix this you should:

1. Run `find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch` to remove .DS_Store files from git.
2. Run `git rm -f .idea` to remove the idea folder from git.
3. Add a .gitignore file to the root folder. You can use the one from IFermi: https://github.com/utf/IFermi/blob/master/.gitignore
4. Commit your changes to GitHub.

**Comment by savya10** [comment]
Hi @utf, with step 2, i get  ```fatal: not removing '.idea' recursively without -r```. Would it be okay to allow recursive removal with ```git rm -r .idea```?

**Comment by utf** [comment]
Yeah that will be fine. `git rm` won't delete anything, just remove it from the set of files "tracked" by git.

**Comment by utf** [comment]
Great job fixing all these issues btw!

**Comment by savya10** [comment]
Thanks, all done :)
