### ISSUE TITLE
Remove paper PDFs from example folders

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#20]
We can't redistribute papers as they are copyright protected!

**Comment by utf** [comment]
You could always include a README.md file in each folder containing the reference and a link to the paper.

**Comment by savya10** [comment]
Are the png screenshots of the graphs okay to keep in the folder, or do i need to remove these as well?

**Comment by utf** [comment]
I'm not sure about that actually. Maybe @aronwalsh will know if it's OK to include screenshots of figures from papers (with his experience as a journal editor)?

**Comment by aronwalsh** [comment]
Hmmm... it's easier when the paper is published under a CC-BY license, but that's not the case here. Best practice is to extract the data (using a digitiser tool) and replot,  or to redraw if it's for a schematic diagram.

**Comment by savya10** [comment]
I've removed the pdfs for now, and included the comparison references (MLA format) and the figures which I am comparing them to into some README.md files. It's likely that there will be more changes with the example data so will address this again once the major code changes are done.

**Comment by savya10** [comment]
done :)
