### ISSUE TITLE
Implementing deltaT/T

### ISSUE THREAD

**Issue by savya10** [WMD-group/PyTASER#25]
A lot of TAS spectra in literature use ΔT/T plots instead of just the ΔT plots that are currently used in PyTASER. To enable effective comparison against this data, we need to be able to switch the y-axis into a ΔT/T plot as well. 

However, it is unclear if the denominator in ΔT/T is normalised according to `JDOS_dark` or `JDOS_light` - this seems to vary across literature. Furthermore, the denominator is often zero, despite a non-zero ΔT - this results in the ΔT/T shooting to infinity. While we could use a filter to ignore normalisation of `T~0` values, there is no indicator of how this would affect the accuracy of the plot. 
As such, we need a clear indication of how ΔT/T works.

**Comment by kavanase** [comment]
I think the problem with this is that T is volume dependent, right? But ΔT/T isn't, so I think what we plot is already much closer to this.  
Regarding the denominator, I think it's just the absorption/transmission in the dark. Some papers also seem to use just ΔT or ΔA as well though?

**Comment by savya10** [comment]
Discussed - no longer necessary as ΔT/T will vary with experimental setup. Total TAS spectrum will now be using the unit ΔA
