### ISSUE TITLE
Automatic transition selection

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#27]
I think the best approach for automatically selecting which transitions to plot is as follows:

1. Get the maximum absolute value of each transition within the plotting region.
2. Find the largest of all maximums.
3. Include transitions whose maximum value is within X% of largest maximum.

The X% should be an adjustable parameter, e.g., `transition_cutoff`. By default, I think a good value is 0.97 (e.g., 97%) but this could be tuned.

**Comment by savya10** [comment]
Done!
