### ISSUE TITLE
Create pytaser package

### ISSUE THREAD

**Issue by utf** [WMD-group/PyTASER#3]
Currently your python files are all in the root directory and cannot be installed as package.

The next step is to actually create a python package and also a `setup.py` file so pytaser can be pip installed.

You can do this in 3 steps.

1. Create a folder called `pytaser` and put the `tas.py`, `generator.py` and  `plotter.py` in that folder. Also create an empty file called `__init__.py` in the folder too. This file lets python know you've created a package. Make the sure `pytaser` folder is lower case as all python packages shouldn't contain capital letters.
2. Update all the pytaser imports in your package and examples. E.g., `import generator` would become `from pytaser import generator`. Similarly, `from tas import Tas` would become `from pytaser.tas import Tas`. Make sure you do this in your examples too.
3. Create a `setup.py` file that will allow your package to be pip installable. This defines several things, like the dependencies of the package and some metadata. You can see an example `setup.py` file [here](https://github.com/utf/IFermi/blob/master/setup.py). Note you won't need the `extras_require` and `entry_points` parts from that example.

Please merge #2 before making these changes.

**Comment by savya10** [comment]
done :)
