### ISSUE TITLE
Extra pages in documentation

### ISSUE THREAD

**Issue by savya10** [WMD-group/PyTASER#37]
It would be beneficial for the docs to have a page on the theory behind pytaser, as well as a page on preferred settings/tips for new users.

**Comment by kavanase** [comment]
@savya10 I would suggest that this can be achieved by either copying the text from the JOSS draft (as done for [`easyunfold`'s theory page](https://smtg-bham.github.io/easyunfold/theory.html)), or the lazier option would be to include a link to the JOSS paper when accepted.

**Comment by kavanase** [comment]
This is partially achieved now with the addition of the `Background` section to the docs. 
I propose once the JOSS is published (soon 🙏 ), we just add a link to this saying "More details on the theory behind TAS can be found in the JOSS paper." (linked)

**Comment by kavanase** [comment]
Now handled by [5b8a6d5](https://github.com/WMD-group/PyTASER/commit/5b8a6d5b6343033fb20122db6f19f9b40cde500c)
